Update pre-commit

diff --git a/hook/pre-commit b/hook/pre-commit
--- a/hook/pre-commit
+++ b/hook/pre-commit
@@ -21,6 +21,7 @@ if ! command -v gitleaks &> /dev/null; then
 
     current_os=""
     current_arch=""
+    destination_dir=""
 
     get_os() {
     if [ -n "$OSTYPE" ]; then
@@ -85,6 +86,12 @@ if ! command -v gitleaks &> /dev/null; then
         ;;
     esac
 
+    if [ $current_os = "windows" ]; then
+       $destination_dir=bin
+    else
+       $destination_dir=.local/bin
+    fi
+
     if [ $current_os = "windows" ] || [ $current_arch = "armv6" ] || [ $current_arch = "armv7" ]; then
         file_format="zip"
     else
@@ -99,23 +106,29 @@ if ! command -v gitleaks &> /dev/null; then
         exit 1
     fi
 
-    if [ ! -d ~/.local/bin ]; then
-        echo "Creating ~/.local/bin directory"
-        mkdir ~/.local/bin
+    if [ ! -d ~/$destination_dir ]; then
+        echo "Creating ~/$destination_dir directory"
+        mkdir -p ~/$destination_dir
         if [ $? -ne 0 ]; then
-            echo "Failed to create ~/.local/bin directory"
+            echo "Failed to create ~/$destination_dir directory"
             exit 1
         fi
     fi
 
-    if ! echo $PATH | grep -q "/.local/bin"; then
-        echo "Adding ~/.local/bin to PATH"
-        echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
+    if ! echo $PATH | grep -q "$HOME/$destination_dir"; then
+        echo "Adding ~/$destination_dir to PATH"
+        echo 'export PATH="$HOME/$destination_dir:$PATH"' >> ~/.bashrc
         source ~/.bashrc
     fi
 
+
     if [ $file_format = "zip" ]; then
-        unzip -o gitleaks.${file_format} -d ~/.local/bin
+        if [ $current_os = "windows" ]; then
+            unzip -o /tmp/gitleaks.${file_format} -d ~/bin
+        else
+            unzip -o /tmp/gitleaks.${file_format} -d ~/.local/bin
+        fi
+        
     else
         tar -xzf gitleaks.${file_format} -C ~/.local/bin
     fi
@@ -124,10 +137,12 @@ if ! command -v gitleaks &> /dev/null; then
         exit 1
     fi
 
-    chmod +x ~/.local/bin/gitleaks
-    if [ $? -ne 0 ]; then
-        echo "Failed to make gitleaks executable"
-        exit 1
+    if [ ! $current_os = "windows" ]; then
+        chmod +x ~/$destination_dir/gitleaks
+        if [ $? -ne 0 ]; then
+            echo "Failed to make gitleaks executable"
+            exit 1
+        fi
     fi
 
     rm /tmp/gitleaks.${file_format}
@@ -136,5 +151,6 @@ if ! command -v gitleaks &> /dev/null; then
         exit 1
     fi
 fi
+
 # Run gitleaks
 gitleaks detect --source . --redact --report-path report.json
